# Generated by Django 4.1.5 on 2023-01-11 03:41

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "hash_email",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("email", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=64)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="VN"
                    ),
                ),
            ],
        ),
    ]
